# Corelight Data Dictionary for humio-organization-corelight-demo #repo

| Field Name | Description | Relevance to a SOC Analyst |
| --- | --- | --- |
| `#path` | The type of log data (e.g., "ssl", "http", "dns") | This field is important for understanding the context of the log entry. It can help analysts identify the type of network traffic or activity that generated the log, which can be crucial for incident response and threat hunting. |
| `id.orig_h` | The originating host IP address | This field can help identify the source of potential malicious activity. Analysts can use this information to trace back network events to a specific host, which is crucial for incident investigation and response. |
| `ts` | The timestamp of the event | The timestamp is critical for understanding the sequence of events during an incident. It can help analysts correlate events across different log sources and establish a timeline of activities. |
| `#repo` | The repository where the log data is stored | Knowing where the log data is stored can help analysts retrieve additional data if needed. It can also be useful for managing and organizing log data. |
| `id.orig_p` | The originating port number | The originating port can provide information about the type of service or application that generated the network traffic. This can be useful for identifying unusual or suspicious activity. |
| `version` | The version of the protocol (e.g., "TLSv10" for SSL, "1.1" for HTTP) | The protocol version can provide insights into the security posture of the network. Older protocol versions may have known vulnerabilities and their usage can indicate security misconfigurations or outdated systems. |
| `cipher` | The cipher suite used in the SSL/TLS connection | The cipher suite can provide insights into the security of the encrypted network traffic. Weak or outdated cipher suites can expose the network to certain types of attacks. |
| `resumed` | Indicates whether the SSL/TLS session was resumed | Session resumption can improve performance by skipping the full SSL/TLS handshake. However, it can also pose security risks if not properly managed. Analysts can monitor this field to ensure secure configurations. |
| `ja3s` | The JA3S fingerprint of the server in the SSL/TLS connection | JA3S fingerprints can be used to identify servers based on their SSL/TLS characteristics. This can be useful for detecting malicious servers or tracking the activity of known malicious entities. |
| `uid` | A unique identifier for the connection | The unique identifier can be used to correlate different log entries related to the same network connection. This can be useful for tracking the activities of a specific connection over time. |
| `established` | Indicates whether the SSL/TLS connection was established | This field can help analysts identify successful connections, which might be relevant when investigating incidents or reviewing network activity. |
| `@timestamp.nanos` | The nanosecond component of the timestamp | The nanosecond component can provide a more precise timing of events, which can be useful when analyzing events that occur in quick succession. |
| `_system_name` | The name of the system that generated the log | Knowing the system that generated the log can help analysts understand the source of the data and can be useful when investigating incidents that involve multiple systems. |
| `@id` | A unique identifier for the log entry | The unique identifier can be used to correlate different log entries related to the same event or incident. This can be useful for tracking the activities of a specific event over time. |
| `@timestamp` | The timestamp of the event in milliseconds | The timestamp in milliseconds can provide a more precise timing of events, which can be useful when analyzing events that occur in quick succession. |
| `@ingesttimestamp` | The timestamp when the log was ingested | The ingestion timestamp can be useful for understanding the delay between when an event occurred and when it was logged. This can be important for ensuring timely detection and response to incidents. |
| `id.resp_h` | The responding host IP address | The responding host can help identify the target of potential malicious activity. Analysts can use this information to identify potential victims or targets in their network. |
| `_write_ts` | The timestamp when the log was written | The write timestamp can be useful for understanding the delay between when an event occurred and when it was logged. This can be important for ensuring timely detection and response to incidents. |
| `#type` | The type of log data (e.g., "corelight-json") | The type of log data can help analysts understand the format and structure of the data, which can be important for parsing and analyzing the logs. |
| `@timezone` | The timezone of the timestamp | The timezone can be important for correlating events across different systems and geographies. It can help ensure that all timestamps are interpreted correctly. |
| `id.resp_p` | The responding port number | The responding port can provide information about the type of service or application that was targeted by the network traffic. This can be useful for identifying unusual or suspicious activity. |
| `@rawstring` | The raw log data as a string | The raw log data can be useful for troubleshooting or deep-dive investigations. It can provide additional context that might not be captured in the parsed log fields. |
| `ja3` | The JA3 fingerprint of the client in the SSL/TLS connection | JA3 fingerprints can be used to identify clients based on their SSL/TLS characteristics. This can be useful for detecting malicious clients or tracking the activity of known malicious entities. |
